// Adapts the controller's internal bundles to the CalendarModalShell prop
// contract. Props stay grouped end-to-end; this layer only renames
// controller-internal fields to shell-facing ones and derives small defaults.
export default function buildCalendarModalShellProps({
  refs,
  viewState,
  data,
  viewModel,
  selection,
  editors,
  quickActions,
  agenda,
  floating,
  handlers,
  search,
  availableCalendarViews,
}) {
  return {
    refs: {
      panelRef: refs.panelRef,
      scrollRef: refs.scrollRef,
      contextRailRef: refs.contextRailRef,
      agendaRailRef: refs.agendaRailRef,
    },
    viewState: {
      view: viewState.view,
      viewYear: viewState.viewYear,
      viewMonth: viewState.viewMonth,
      currentYear: viewState.currentYear,
      currentMonth: viewState.currentMonth,
      todayDate: viewState.todayDate,
      suppressFocusRing: viewState.suppressFocusRing,
    },
    viewModel: {
      panelWidth: viewModel.panelWidth,
      layout: viewModel.layout,
      monthName: viewModel.monthName,
      monthYear: viewModel.monthYear,
      canGoPrev: viewModel.canGoPrev,
      computed: viewModel.computed,
      itemsByDay: viewModel.itemsByDay,
      itemsByDate: viewModel.computed.itemsByDate || {},
      cellMetaByDate: viewModel.computed.cellMetaByDate || {},
      showGridSkeleton: viewModel.showGridSkeleton,
      buildFallbackDayState: viewModel.buildFallbackDayState,
      showDetail: viewModel.showDetail,
      showEmptySelection: viewModel.showEmptySelection,
      effectiveSelectedItemId: viewModel.effectiveSelectedItemId,
      selectedDayState: viewModel.selectedDayState,
      selectedItems: viewModel.selectedItems,
      ghostPreview: viewModel.ghostPreview,
      floatingDetailLabel: viewModel.floatingDetailLabel,
    },
    data: {
      activeView: data.activeView,
      HeaderExtras: data.activeView.HeaderExtras,
      viewData: data.viewData,
      weatherData: data.weatherData,
      isMonthCached: data.isMonthCached,
      getMonthEvents: data.getMonthEvents,
      getMonthDeadlines: data.getMonthDeadlines,
      eventsRange: data.eventsRange,
      deadlinesRange: data.deadlinesRange,
      dataRevision: data.dataRevision,
    },
    selection: {
      selectedDay: selection.activeSelectedDay,
      selectedDateKey: selection.activeSelectedDateKey,
      setSelectedDay: selection.setSelectedDay,
      setSelectedDateKey: selection.setSelectedDateKey,
      setSelectedItemId: selection.setSelectedItemId,
    },
    editors: {
      eventEditor: editors.eventEditor,
      deadlineEditor: editors.deadlineEditor,
      setDeadlineEditor: editors.setDeadlineEditor,
      closeEventEditor: handlers.closeEventEditor,
      onDeadlineDraftPreviewChange: editors.setDeadlineDraftPreview,
    },
    quickActions: {
      eventQuickActions: quickActions.eventQuickActions,
      deadlineQuickActions: quickActions.deadlineQuickActions,
    },
    agenda: {
      agendaScrollCommand: agenda.agendaScrollCommand,
      agendaEntryTargetDateKey: agenda.agendaEntryTargetDateKey,
      onAgendaPassiveDateChange: agenda.onAgendaPassiveDateChange,
      onAgendaDateAction: agenda.onAgendaDateAction,
      onAgendaEventAction: agenda.onAgendaEventAction,
      miniCalendarActions: {
        onDateAction: agenda.onMiniCalendarDateAction,
        onDateCreate: agenda.onMiniCalendarDateCreate,
      },
      onAgendaDirtyBlocked: floating.shakeFloatingEditor,
      onGridDateAction: agenda.scrollAgendaToDate,
      onGridEventAction: agenda.scrollAgendaToEvent,
    },
    floating: {
      floatingDetail: floating.floatingDetail,
      onOpenFloatingDetail: floating.openFloatingDetail,
      onCloseFloatingDetail: floating.closeFloatingDetail,
      onFloatingDetailDragged: floating.setFloatingDetailDragged,
      onOpenFloatingEventCreate: floating.openFloatingEventCreate,
      onOpenFloatingEventEdit: floating.openFloatingEventEdit,
      onOpenFloatingDeadlineCreate: floating.openFloatingDeadlineCreate,
      onOpenFloatingDeadlineEdit: floating.openFloatingDeadlineEdit,
      onCancelFloatingEditor: floating.cancelFloatingEditor,
      onFloatingEditorDirtyChange: floating.setFloatingEditorDirty,
      onFloatingEditorSaveRequest: floating.setFloatingEditorSaveRequest,
      onShakeFloatingEditor: floating.shakeFloatingEditor,
      onFloatingDeadlineSaved: floating.handleFloatingDeadlineSaved,
      onFloatingDeadlineDeleted: floating.handleFloatingDeadlineDeleted,
    },
    handlers: {
      navigateMonth: handlers.navigateMonth,
      jumpToMonth: handlers.jumpToMonth,
      onViewChange: handlers.handleViewChange,
      onClose: handlers.closeCalendarModal,
      suppressOutsideClick: handlers.suppressOutsideClick,
      focusDeadlineTask: handlers.focusDeadlineTask,
      onDisplayMonthChange: handlers.onDisplayMonthChange,
      onLabelMonthChange: handlers.onLabelMonthChange,
      onFetchSettle: handlers.onFetchSettle,
    },
    search,
    availableCalendarViews: availableCalendarViews ?? ["events"],
  };
}
