export default function buildCalendarModalShellProps({
  refs,
  viewState,
  data,
  viewModel,
  selection,
  editors,
  quickActions,
  agenda,
  floating,
  handlers,
}) {
  return {
    panelRef: refs.panelRef,
    scrollRef: refs.scrollRef,
    contextRailRef: refs.contextRailRef,
    panelWidth: viewModel.panelWidth,
    layout: viewModel.layout,
    view: viewState.view,
    monthName: viewModel.monthName,
    monthYear: viewModel.monthYear,
    canGoPrev: viewModel.canGoPrev,
    navigateMonth: handlers.navigateMonth,
    monthMotionDirection: viewState.monthMotionDirection,
    workspaceTransientCloseToken: viewState.workspaceTransientCloseToken,
    onViewChange: handlers.handleViewChange,
    HeaderExtras: data.activeView.HeaderExtras,
    viewData: data.viewData,
    weatherData: data.weatherData,
    computed: viewModel.computed,
    suppressOutsideClick: handlers.suppressOutsideClick,
    eventEditor: editors.eventEditor,
    selectedDay: selection.activeSelectedDay,
    selectedDateKey: selection.activeSelectedDateKey,
    viewYear: viewState.viewYear,
    viewMonth: viewState.viewMonth,
    setDeadlineEditor: editors.setDeadlineEditor,
    onClose: handlers.closeCalendarModal,
    activeView: data.activeView,
    currentYear: viewState.currentYear,
    currentMonth: viewState.currentMonth,
    todayDate: viewState.todayDate,
    firstDay: viewModel.firstDay,
    daysInMonth: viewModel.daysInMonth,
    trailingEmpty: viewModel.trailingEmpty,
    itemsByDay: viewModel.itemsByDay,
    itemsByDate: viewModel.computed.itemsByDate || {},
    cellMetaByDate: viewModel.computed.cellMetaByDate || {},
    showGridSkeleton: viewModel.showGridSkeleton,
    buildFallbackDayState: viewModel.buildFallbackDayState,
    closeEventEditor: handlers.closeEventEditor,
    setSelectedDay: selection.setSelectedDay,
    setSelectedDateKey: selection.setSelectedDateKey,
    setSelectedItemId: selection.setSelectedItemId,
    eventQuickActions: quickActions.eventQuickActions,
    deadlineQuickActions: quickActions.deadlineQuickActions,
    agendaRailRef: refs.agendaRailRef,
    agendaScrollCommand: agenda.agendaScrollCommand,
    onAgendaPassiveDateChange: agenda.onAgendaPassiveDateChange,
    onAgendaDateAction: agenda.onAgendaDateAction,
    onAgendaEventAction: agenda.onAgendaEventAction,
    onAgendaDirtyBlocked: floating.shakeFloatingEditor,
    onGridDateAction: agenda.scrollAgendaToDate,
    onGridEventAction: agenda.scrollAgendaToEvent,
    showDetail: viewModel.showDetail,
    showEmptySelection: viewModel.showEmptySelection,
    effectiveSelectedItemId: viewModel.effectiveSelectedItemId,
    selectedDayState: viewModel.selectedDayState,
    selectedItems: viewModel.selectedItems,
    deadlineEditor: editors.deadlineEditor,
    focusDeadlineTask: handlers.focusDeadlineTask,
    ghostPreview: viewModel.ghostPreview,
    onDeadlineDraftPreviewChange: editors.setDeadlineDraftPreview,
    floatingDetail: floating.floatingDetail,
    floatingDetailLabel: viewModel.floatingDetailLabel,
    onOpenFloatingDetail: floating.openFloatingDetail,
    onCloseFloatingDetail: floating.closeFloatingDetail,
    onParkFloatingDetail: floating.parkFloatingDetail,
    onFloatingDetailDragged: floating.setFloatingDetailDragged,
    onReanchorFloatingDetail: floating.reanchorFloatingDetail,
    onOpenFloatingEventCreate: floating.openFloatingEventCreate,
    onOpenFloatingEventEdit: floating.openFloatingEventEdit,
    onOpenFloatingDeadlineCreate: floating.openFloatingDeadlineCreate,
    onOpenFloatingDeadlineEdit: floating.openFloatingDeadlineEdit,
    onCancelFloatingEditor: floating.cancelFloatingEditor,
    onFloatingEditorDirtyChange: floating.setFloatingEditorDirty,
    onFloatingEditorSaveRequest: floating.setFloatingEditorSaveRequest,
    onShakeFloatingEditor: floating.shakeFloatingEditor,
    onFloatingDeadlineSaved: floating.handleFloatingDeadlineSaved,
    onFloatingDeadlineDeleted: floating.handleFloatingDeadlineDeleted,
    suppressFocusRing: viewState.suppressFocusRing,
  };
}
